src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/store/urls.py
from django.urls import path
from .api import *
from .views import (
    Home,
    detail_view,
    add_to_cart, 
    CheckoutView, 
    remove_from_cart, 
    ShirtView, 
    SportsView, 
    OutWearView,
    search_item,
    OrderView,
    remove_one_item_from_cart,
    payment_view,
    stripe_config,
    create_checkout_session,
    payment_success,
    payment_cancel,
    save_button,
    saved_posts
)


app_name="store"

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('<int:pk>/', detail_view, name="detail"),
    path('<int:pk>/add_to_cart/', add_to_cart, name='add_to_cart'),
    path('<int:pk>/rm-item/', remove_from_cart, name="remove_item"),
    path('shirt/', ShirtView.as_view(), name='shirt'),
    path('sport/', SportsView.as_view(), name='sport'),
    path('outwear/', OutWearView.as_view(), name='outwear'),
    path('search/', search_item, name="search"),
    path('order/', OrderView.as_view(), name="order"),
    path('<int:pk>/remove-one', remove_one_item_from_cart, name="remove_one_item"),
    path('cart/', CheckoutView.as_view(), name='checkout'),
    path('wish/<int:pk>/', save_button, name='save' ),
    path('wishl/', saved_posts, name='wishlist'),

    path('config/', stripe_config),
    path('create-checkout-session/', create_checkout_session), # new
    path('success/', payment_success),
    path('cancel/', payment_cancel),

    # api urls
    path('<int:pk>/item-detail-api/', item_detail_api, name="item_detail_api"),
    path("item-list-api/", ApiItemList.as_view(), name="item_list_api")
]

src/users/urls.py
import imp
from re import template
from django.urls import path
from django.contrib.auth import views
from .views import register, logout_view, profile


app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('register/', register, name="register"),
    path('logout/', logout_view, name="logout"),
    path('profile/', profile, name="profile")
]

src/templates/cancel.html
<h1>Cancel</h1>

src/templates/footer.html
  <!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn footer--body">

<!--Call to action-->

<!--/.Call to action-->


<!-- Social icons -->
    <div class="pb-4 pt-1">
        <a href="#" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <a href="#" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
        </a>

        <a href="#" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
        </a>

        <a href="#" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
        </a>

        <a href="#" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
        </a>

        <a href="#" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
        </a>

        <a href="#" target="_blank">
        <i class="fab fa-github mr-3"></i>
        </a>

        <a href="#" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
        </a>
    </div>
<!-- Social icons --> 

<!--Copyright-->
    <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="#" target="_blank"> </a>
    </div>
<!--/.Copyright-->

</footer>
  <!--/.Footer-->

src/templates/home-page.html
{% extends "base.html" %}

{% load static %}


{% block content %}
  <main class="mt-5 pt-2">
    <div class="container">
      {% include 'categories.html' %}
      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for instance in object_list %}

          <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4">
                <!--Card-->
                <div class="card">
                    <!--Card image-->
                    <div class="view overlay">
                      <img src="{{ instance.image.url }}" class="card-img-top"
                        alt="">
                      <a href="{% url 'store:detail' instance.pk %}">
                        <div class="mask rgba-white-slight"></div>
                      </a>
                    </div>
                    <!--Card image-->

                    <!--Card content-->
                    <div class="card-body text-center">
                      <!--Category & Title-->
                      <a href="{% url 'store:detail' instance.pk %}" class="grey-text">
                        <h5>{{ instance.category }}</h5>
                      </a>
                      <h5>
                        <strong>
                          <a href="{% url 'store:detail' instance.pk %}" class="dark-grey-text">{{instance.title}}
                          </a>
                          {% if instance.label == "SALE" %}
                          <span class="badge badge-pill warning-color">{{ instance.label }}</span>
                          {% elif instance.label == "NEW" %}
                          <span class="badge badge-pill danger-color">{{ instance.label }}</span>
                          {% endif %}
                        </strong>
                        
                      </h5>
                      
                      <h4 class="font-weight-bold blue-text">
                        <strong>
                          {% if instance.discount_price %}
                            {{instance.discount_price}}$
                          {% else %}
                            {{instance.price}}$
                          {% endif %}
                        </strong>
                      </h4>

                    </div>
                    <!--Card content-->
                </div>
                <!--Card-->
              </div>
          {% endfor %}

          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

          </div>
          <!--Fourth column-->

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center fadeIn m-3">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if is_paginated %}
            <ul class="pagination pg-blue">

              {% if page_obj.has_previous %}
                <li class="page-item">
                  <a class="btn btn-outline-info mb-4" href="?page=1">
                    <span>&laquo;</span>
                  </a>
                </li>
                <li class="page-item">
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
              {% endif %}

              {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                  <li class="page-item">
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                  <li class="page-item">
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  </li>
                {% endif %}
              {% endfor %}

              <!-- <li class="page-item">
                <span class="current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
              </li> -->
              <!-- <li class="page-item active">
                <a class="page-link" href="#">{{ object_list.number }}
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">{{ object_list.paginator.num_pages }}</a>
              </li> -->
              {% if page_obj.has_next %}
              <li class="page-item">
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
              </li>
              <li class="page-item">
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
              </li>
              {% endif %}
            </ul>
          {% endif %}
      </nav>
      <!--Pagination-->

    </div>
  </main>
  {% comment %} {% include "footer.html" %} {% endcomment %}
{% endblock content %}

src/templates/nav.html
<!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'store:home' %}">
        <strong class="blue-text">DEC</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Search the items -->
        <ul class="navbar-nav mr-auto">
          <form class="form-inline" action="{% url 'store:search' %}" method="GET">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="q">
            </div>
          </form>
        </ul>
      
        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item mr-3">
            {% csrf_token %}
            <a href="{% url 'users:profile' %}">
              <button type="submit" class="nav-link waves-effect" style="background: none; border:none"><span>Profile</span></button>
            </a>
          </li>
          <li class="nav-item mr-3">
            <a href="{% url 'store:wishlist' %}">
              <button type="submit" class="nav-link waves-effect" style="background: none; border:none"><span>WishList</span></button>
            </a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link waves-effect" href="{% url 'store:order' %}">
              <span class="badge red z-depth-1 mr-1"></span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <form method="Post" action="{% url 'users:logout' %}">
              {% csrf_token %}
              <button type="submit" class="nav-link waves-effect" style="background: none; border:none"><span>Logout</span></button>
            </form>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="waves-effect nav-link" href="{% url 'users:login' %}">
                <b>Login</b>
              </a>
            </li>

            <li class="nav-item">
              <a class="waves-effect nav-link" href="{% url 'users:register' %}">
                <b>Register</b>
              </a>
            </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

src/templates/order.html
{% extends "base.html" %}
{% load static %}


{% block content %}
  <main class="mt-5 pt-5" style="margin-bottom:135px">
    <div class="container">
      <!--Section: Products v.3-->
      <h2 class="mb-3 pb-2 mt-3">Your Cart</h2>
        <div class="table-responsive">
            <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">quantity</th>
                      <th scope="col">price</th>
                      <th scope="col">total</th>
                    </tr>
                  </thead>
                    {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.title }}</td>
                            <td>
                              <a href="{% url 'store:remove_one_item' order_item.item.pk %}"><i class="fas fa-minus-circle"></i></a>
                              {{ order_item.quantity }}
                              <a href="{% url 'store:add_to_cart' order_item.item.pk %}"><i class="fas fa-plus-circle"></i></a>
                            </td>
                            {% if order_item.item.discount_price %}
                                <td>${{ order_item.item.discount_price }}</td>
                                <td>${{ order_item.get_total_discount_price }}
                                  <a style="color:#2196f3" href="{% url 'store:remove_item' order_item.item.pk %}">
                                    <i class="fas fa-trash float-right"></i>
                                  </a>
                                </td>
                            {% else %}
                                <td>${{ order_item.item.price }}</td>
                                <td>${{ order_item.get_total_price }}
                                  <a style="color:#2196f3" href="{% url 'store:remove_item' order_item.item.pk %}">
                                    <i class="fas fa-trash float-right"></i>
                                  </a>
                                </td>
                            {% endif %}
                        </tr>
                        {% empty %}
                        <tr>
                          <td colspan="5"><b>Your cart is empty</b></td>
                          <a class="btn btn-primary float-right" href="{% url 'store:home' %}">Continue shopping</a>
                        </tr>
                    {% endfor %}
                    {% if object.get_total %}
                        <tr> 
                          <td colspan="4"><b>Total price</b></td>
                          <td>
                            <b>${{ object.get_total }}</b>
                          </td>

                        </tr>
                        <tr>
                          <td colspan="5">
                            <a class="btn btn-warning float-right ml-3" href="{% url 'store:checkout' %}">Checkout</a>
                            <a class="btn btn-primary float-right" href="{% url 'store:home' %}">Continue shopping</a>
                          </td>
                        </tr>
                    {% endif %}
                  </tbody>
            </table>
    
        </div>

    </div>
  </main>
  {% include "footer.html" %}
{% endblock content %}

src/templates/outwear-list.html
{% extends "base.html" %}

{% load static %}


{% block content %}
  <main class="mt-5 pt-2">
    <div class="container" style="margin-bottom: 165px">

      {% include 'categories.html' %}

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for instance in object_list %}

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card">
                <!--Card image-->
                <div class="view overlay">
                  <img src="{{ instance.image.url }}" class="card-img-top"
                    alt="">
                  <a href="{% url 'store:detail' instance.pk %}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
                <!--Card image-->

                <!--Card content-->
                <div class="card-body text-center">
                  <!--Category & Title-->
                  <a href="{% url 'store:detail' instance.pk %}" class="grey-text">
                    <h5>{{ instance.category }}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="" class="dark-grey-text">{{instance.title}}
                        <span class="badge badge-pill danger-color">NEW</span>
                      </a>
                    </strong>
                  </h5>

                  <h4 class="font-weight-bold blue-text">
                    <strong>
                      {% if instance.discount_price %}
                        {{instance.discount_price}}$
                      {% else %}
                        {{instance.price}}$
                      {% endif %}
                    </strong>
                  </h4>

                </div>
                <!--Card content-->
            </div>
            <!--Card-->
          </div>
          {% endfor %}

          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

          </div>
          <!--Fourth column-->

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if is_paginated %}
            <ul class="pagination pg-blue">

              {% if page_obj.has_previous %}
                <li class="page-item">
                  <a class="btn btn-outline-info mb-4" href="?page=1">
                    <span>&laquo;</span>
                  </a>
                </li>
                <li class="page-item">
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
              {% endif %}

              {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                  <li class="page-item">
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                  <li class="page-item">
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  </li>
                {% endif %}
              {% endfor %}

              <!-- <li class="page-item">
                <span class="current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
              </li> -->
              <!-- <li class="page-item active">
                <a class="page-link" href="#">{{ object_list.number }}
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">{{ object_list.paginator.num_pages }}</a>
              </li> -->
              {% if page_obj.has_next %}
              <li class="page-item">
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
              </li>
              <li class="page-item">
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
              </li>
              {% endif %}
            </ul>
          {% endif %}
      </nav>
      <!--Pagination-->

    </div>
  </main>
  {% include "footer.html" %}
{% endblock content %}

src/templates/product-page.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <a href="{{ item.image.url }}">
            <img src="{{ item.image.url }}" class="img-fluid" alt="">
          </a>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              {% if item.category == "shirt" %}
                <a href="{% url 'store:shirt' %}">
                  <span class="badge purple mr-1">{{ item.category }}</span>
                </a>
              {% elif item.category == "sport" %}
                <a href="{% url 'store:shirt' %}">
                  <span class="badge purple mr-1">{{ item.category }}</span>
                </a>
              {% elif item.category == "outwears" %}
                <a href="{% url 'store:shirt' %}">
                  <span class="badge purple mr-1">{{ item.category }}</span>
                </a>
              {% endif %}
            </div>
            {% if item.discount_price %}
              <p class="lead">
                <span class="mr-1">
                  <del>${{ item.price }}</del>
                </span>
                <span>${{ item.discount_price }}</span>
              </p>
            {% else %}
              <p class="lead">
                <span>${{ item.price }}</span>
              </p>
            {% endif %}
            <p class="lead font-weight-bold">Description</p>

            <p class="mb-5">{{ item.description }}</p>

            <!-- <form class="d-flex justify-content-left">
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> -->
            <a href="{{ item.get_add_to_cart_url }}">
              <button class="btn btn-primary btn-md my-0 p" >Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>
            </a>
            <a href="{% url 'store:remove_item' item.pk %}">
              <button class="btn btn-danger btn-md my-0 p" >Remove from cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>
            </a>
            {% if request.user.is_authenticated %}
              {% if post == True %}
                <button id='save-button' class="btn btn-info btn-md my-0 p m-1">
                  wished
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>
              {% else %}
                <button id='save-button' class="btn btn-info btn-md my-0 p m-1">
                  wish
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>
              {% endif %}
            {% endif %}
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center mb-5">

          <h4 class="my-4 h4">Additional information</h4>

          <p>{{ item.info }}</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn" style="margin-bottom: 100px">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-5">
          <a href="{{ item.image_2.url }}">
            <img src="{{ item.image_2.url }}" class="img-fluid" alt="">
          </a>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-5">
          <a href="{{ item.image_3.url }}">
            <img src="{{ item.image_3.url }}" class="img-fluid" alt="">
          </a>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <a href="{{ item.image_4.url }}">
            <img src="{{ item.image_4.url }}" class="img-fluid" alt="">
          </a>
        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  {% include "footer.html" %}
  <script>
    var a = "{{post}}";
    $(document).ready(function(){
      $("#save-button").on('click',function(e){
        {% comment %} e.preventDefault(); {% endcomment %}
        $.ajax({
          type : 'POST',
          url : "{% url 'store:save' item.pk %}",
          data : {
            posted: $('#save-button').val(),
            csrfmiddlewaretoken: '{{ csrf_token }}',
            action: 'post'
          },
          success: function(response) {
            console.log(a);
            console.log(typeof a);
            if (a === "True") {
              console.log(a);
              console.log(typeof a);
              $("#save-button").html("wished <i class='fas fa-shopping-cart ml-1'></i>");
            } else {
              console.log(a);
              console.log(typeof a);
              $("#save-button").html("wish <i class='fas fa-shopping-cart ml-1'></i>");
            }
            location.reload();

            },
              error: function (xhr, errmsg, err){

            }
          });
      })
    })
  </script>
{% endblock content %}

src/templates/saved_posts.html
{% extends 'base.html' %}

{% block content %}
<main class="mt-5 pt-2">
    <div class="container">
        <section class="text-center mb-4">
            <h1 class="pt-5 mt-5 ml-5 mb-5" style="font-size:25px">your wish list contains <b>{{ posts.count }}</b> items</h1>

            <!--Grid row-->
            <div class="row wow fadeIn">
                {% for instance in posts %}

                    <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4">
                    <!--Card-->
                    <div class="card">
                        <!--Card image-->
                        <div class="view overlay">
                        <img src="{{ instance.image.url }}" class="card-img-top"
                            alt="">
                        <a href="{% url 'store:detail' instance.pk %}">
                            <div class="mask rgba-white-slight"></div>
                        </a>
                        </div>
                        <!--Card image-->

                        <!--Card content-->
                        <div class="card-body text-center">
                        <!--Category & Title-->
                        <a href="{% url 'store:detail' instance.pk %}" class="grey-text">
                            <h5>{{ instance.category }}</h5>
                        </a>
                        <h5>
                            <strong>
                            <a href="{% url 'store:detail' instance.pk %}" class="dark-grey-text">{{instance.title}}
                            </a>
                            {% if instance.label == "SALE" %}
                            <span class="badge badge-pill warning-color">{{ instance.label }}</span>
                            {% elif instance.label == "NEW" %}
                            <span class="badge badge-pill danger-color">{{ instance.label }}</span>
                            {% endif %}
                            </strong>
                            
                        </h5>
                        
                        <h4 class="font-weight-bold blue-text">
                            <strong>
                            {% if instance.discount_price %}
                                {{instance.discount_price}}$
                            {% else %}
                                {{instance.price}}$
                            {% endif %}
                            </strong>
                        </h4>

                        </div>
                        <!--Card content-->
                    </div>
                    <!--Card-->
                </div>
                {% endfor %}

            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4">

            </div>
            <!--Fourth column-->

                    </div>
                    <!--Grid row-->

                    </section>
                    <!--Section: Products v.3-->

                    <!--Pagination-->
                    <nav class="d-flex justify-content-center fadeIn m-3">
                        <!--Arrow left-->
                        {% if is_paginated %}
                        <ul class="pagination pg-blue">

                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="btn btn-outline-info mb-4" href="?page=1">
                                <span>&laquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            </li>
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                                {% if page_obj.number == num %}
                                    <li class="page-item">
                                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                                    </li>
                                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                    <li class="page-item">
                                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <li class="page-item">
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                            </li>
                            <li class="page-item">
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                            </li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </nav>
                    <!--Pagination-->

                    </div>
    </div>
</main>    
{% endblock %}

src/templates/success.html
<h1> Success </h1>

src/templates/wish-page.html
{% extends 'base.html' %}

{% block content %}

{% for instance in object_list %}
    <h1>{instance.items.name}</h1>
{% endfor %}

{% endblock content %}